// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

type Mutation struct {
}

type Query struct {
}

// Holds a payload of a role input - label, id, display name and technical name
type RoleInput struct {
	DisplayName   string `json:"displayName"`
	TechnicalName string `json:"technicalName"`
}
