// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

// Contains all roles that are granted to an user
type GrantedUser struct {
	User  *User   `json:"user"`
	Roles []*Role `json:"roles,omitempty"`
}

// Is a list of the users and their roles
type GrantedUserConnection struct {
	Users []*GrantedUser `json:"users,omitempty"`
	//  a number of granted users in the list
	PageInfo *PageInfo `json:"pageInfo"`
}

type Mutation struct {
}

// Holds additional information about the retrieved data
type PageInfo struct {
	OwnerCount int `json:"ownerCount"`
	TotalCount int `json:"totalCount"`
}

type Query struct {
}

type Resource struct {
	Name      string  `json:"name"`
	Namespace *string `json:"namespace,omitempty"`
}

// Represents a role that can be granted to an user or group of users
type Role struct {
	//  Is a human readable name of the role
	DisplayName string `json:"displayName"`
	//  Is an identifier of the role
	TechnicalName string `json:"technicalName"`
}

type SortByInput struct {
	Field     SortableFields `json:"field"`
	Direction SortDirection  `json:"direction"`
}

// Represents an user
type User struct {
	UserID    string  `json:"userId"`
	Email     string  `json:"email"`
	FirstName *string `json:"firstName,omitempty"`
	LastName  *string `json:"lastName,omitempty"`
}

// List of the users
type UserConnection struct {
	User     []*User   `json:"user"`
	PageInfo *PageInfo `json:"pageInfo,omitempty"`
}

// Holds the information about a specific user and and a list of roles that should be assigned to the user
type UserRoleChange struct {
	UserID string   `json:"userId"`
	Roles  []string `json:"roles"`
}

type SortDirection string

const (
	SortDirectionAsc  SortDirection = "asc"
	SortDirectionDesc SortDirection = "desc"
)

var AllSortDirection = []SortDirection{
	SortDirectionAsc,
	SortDirectionDesc,
}

func (e SortDirection) IsValid() bool {
	switch e {
	case SortDirectionAsc, SortDirectionDesc:
		return true
	}
	return false
}

func (e SortDirection) String() string {
	return string(e)
}

func (e *SortDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortDirection", str)
	}
	return nil
}

func (e SortDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SortDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SortDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SortableFields string

const (
	SortableFieldsUser SortableFields = "user"
)

var AllSortableFields = []SortableFields{
	SortableFieldsUser,
}

func (e SortableFields) IsValid() bool {
	switch e {
	case SortableFieldsUser:
		return true
	}
	return false
}

func (e SortableFields) String() string {
	return string(e)
}

func (e *SortableFields) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortableFields(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortableFields", str)
	}
	return nil
}

func (e SortableFields) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SortableFields) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SortableFields) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
