with-expecter: true
packages:
  # External dependencies only - following the principle of only mocking external services
  # Internal service interfaces should use real implementations in tests

  # OpenFGA - External service
  github.com/openfga/api/proto/openfga/v1:
    config:
      dir: pkg/fga/mocks
      outpkg: mocks
    interfaces:
      OpenFGAServiceClient:
        config:
          mockname: OpenFGAServiceClient

  # Platform-mesh commons FGA store helper - External dependency
  github.com/platform-mesh/golang-commons/fga/store:
    config:
      dir: pkg/fga/mocks
      outpkg: mocks
    interfaces:
      FGAStoreHelper:
        config:
          mockname: FGAStoreHelper

  # Keycloak HTTP client - External service interface (wraps external Keycloak API)
  github.com/platform-mesh/iam-service/pkg/keycloak:
    config:
      dir: pkg/keycloak/mocks
      outpkg: mocks
    interfaces:
      KeycloakClientInterface:
        config:
          mockname: KeycloakClientInterface

