with-expecter: true
packages:
  # third party
  github.com/openfga/api/proto/openfga/v1:
    config:
      dir: pkg/fga/mocks
      outpkg: mocks
    interfaces:
      OpenFGAServiceClient:
        config:
          mockname: OpenFGAServiceClient
  github.com/platform-mesh/golang-commons/fga/store:
    config:
      dir: pkg/fga/mocks
      outpkg: mocks
    interfaces:
      FGAStoreHelper:
        config:
          mockname: FGAStoreHelper


