with-expecter: true
packages:
  github.com/openmfp/iam-service/pkg/db:
    config:
      dir: pkg/db/mocks
      outpkg: mocks
    interfaces:
      UserHooks:
        config:
          mockname: UserHooks
      Service:
        config:
          mockname: Service

