with-expecter: true
packages:
  # third party
  github.com/openfga/api/proto/openfga/v1:
    config:
      dir: pkg/fga/mocks
      outpkg: mocks
    interfaces:
      OpenFGAServiceClient:
        config:
          mockname: OpenFGAServiceClient
  github.com/platform-mesh/golang-commons/fga/store:
    config:
      dir: pkg/fga/mocks
      outpkg: mocks
    interfaces:
      FGAStoreHelper:
        config:
          mockname: FGAStoreHelper

  # internal
  github.com/platform-mesh/iam-service/pkg/db:
    config:
      dir: pkg/db/mocks
      outpkg: mocks
    interfaces:
      UserHooks:
        config:
          mockname: UserHooks
      Service:
        config:
          mockname: DatabaseService
#  github.com/platform-mesh/iam-service/pkg/fga:
#    config:
#      dir: pkg/fga/mocks
#      outpkg: mocks
#    interfaces:
#      Service:
#        config:
#          mockname: Service
#      InviteManger:
#        config:
#          mockname: InviteManger
##      FgaEvents:
##        config:
##          mockname: FgaEvents

