with-expecter: true
packages:
  # third party
  github.com/openfga/api/proto/openfga/v1:
    config:
      dir: pkg/fga/mocks
      outpkg: mocks
    interfaces:
      OpenFGAServiceClient:
        config:
          mockname: OpenFGAServiceClient
  github.com/platform-mesh/golang-commons/fga/store:
    config:
      dir: pkg/fga/mocks
      outpkg: mocks
    interfaces:
      FGAStoreHelper:
        config:
          mockname: FGAStoreHelper
  # IAM service packages
  github.com/platform-mesh/iam-service/pkg/service/keycloak:
    config:
      dir: pkg/service/keycloak/mocks
      outpkg: mocks
    interfaces:
      KeycloakService:
        config:
          mockname: KeycloakService
      KeycloakClientInterface:
        config:
          mockname: KeycloakClientInterface
  github.com/platform-mesh/iam-service/pkg/resolver/api:
    config:
      dir: pkg/resolver/mocks
      outpkg: mocks
    interfaces:
      ResolverService:
        config:
          mockname: ResolverService


