with-expecter: true
packages:
  # External dependencies only - following the principle of only mocking external services
  # Internal service interfaces should use real implementations in tests

  # OpenFGA - External service
  github.com/openfga/api/proto/openfga/v1:
    config:
      dir: pkg/fga/mocks
      outpkg: mocks
    interfaces:
      OpenFGAServiceClient:
        config:
          mockname: OpenFGAServiceClient

  # Platform-mesh commons FGA store helper - External dependency
  github.com/platform-mesh/golang-commons/fga/store:
    config:
      dir: pkg/fga/mocks
      outpkg: mocks
    interfaces:
      FGAStoreHelper:
        config:
          mockname: FGAStoreHelper

  # Keycloak HTTP client - External service interface (wraps external Keycloak API)
  github.com/platform-mesh/iam-service/pkg/keycloak:
    config:
      dir: pkg/keycloak/mocks
      outpkg: mocks
    interfaces:
      KeycloakClientInterface:
        config:
          mockname: KeycloakClientInterface

  github.com/platform-mesh/iam-service/pkg/accountinfo:
    config:
      dir: pkg/accountinfo/mocks
      outpkg: mocks
    interfaces:
      Retriever:
        config:
          mockname: Retriever

  github.com/kcp-dev/sdk/client/clientset/versioned/cluster:
    config:
      dir: pkg/accountinfo/mocks
      outpkg: mocks
    interfaces:
      ClusterInterface:
        config:
          mockname: ClusterInterface

  github.com/kcp-dev/sdk/client/clientset/versioned:
    config:
      dir: pkg/accountinfo/mocks
      outpkg: mocks
    interfaces:
      CoreV1alpha1Interface:
        config:
          mockname: CoreV1alpha1Interface
      Interface:
        config:
          mockname: Interface

  github.com/kcp-dev/sdk/client/clientset/versioned/typed/core/v1alpha1:
    config:
      dir: pkg/accountinfo/mocks
      outpkg: mocks
    interfaces:
      CoreV1alpha1Interface:
        config:
          mockname: CoreV1alpha1Interface
      LogicalClusterInterface:
        config:
          mockname: LogicalClusterInterface

  # Workspace ClientFactory - External dependency for KCP workspace client creation
  github.com/platform-mesh/iam-service/pkg/workspace:
    config:
      dir: pkg/fga/mocks
      outpkg: mocks
    interfaces:
      ClientFactory:
        config:
          mockname: ClientFactory

  # IDMUserChecker - External IDM service dependency (could be Keycloak or other IDM systems)
  github.com/platform-mesh/iam-service/pkg/fga:
    config:
      dir: pkg/fga/mocks
      outpkg: mocks
    interfaces:
      IDMUserChecker:
        config:
          mockname: IDMUserChecker





