exclude:
  paths:
    - ^pkg/mocks/.*
    - ^pkg/graph/*
    - ^pkg/db/mocks/.*
    - ^pkg/resolver/*
    - server.go
    - ^pkg/fga/mocks
    - ^pkg/fga/middleware # nothing to test there
    - ^pkg/fga/server.go
    - cmd/*
    - internal/pkg/*
    - main.go
    - contract-tests/

