version: '3'

vars:
  LOCAL_BIN: bin
tasks:
  setup:mockery:
    internal: true
    cmds:
      - test -s {{.LOCAL_BIN}}/mockery || GOBIN=$(pwd)/{{.LOCAL_BIN}} go install github.com/vektra/mockery/v2@v2.43.2
  ## Setup
  setup:golangci-lint:
    internal: true
    cmds:
      - test -s {{.LOCAL_BIN}}/golangci-lint || GOBIN=$(pwd)/{{.LOCAL_BIN}} go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

  ## Development
  mockery:
    deps: [setup:mockery]
    cmds:
      - "{{.LOCAL_BIN}}/mockery --output=pkg/mocks"
  fmt:
    cmds:
      - go fmt ./...
  lint:
    deps: [setup:golangci-lint, mockery]
    cmds:
      - task: fmt
      - "{{.LOCAL_BIN}}/golangci-lint run --timeout 15m ./..."
  test:
    env:
      GO111MODULE: on
    deps:
      - task: mockery
    cmds:
      - go test ./...
  cover:
    deps:
      - task: mockery
    cmds:
        - go test -coverprofile=coverage.out ./...
  validate:
    cmds:
      - task: lint
      - task: test
