// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	db "github.com/openmfp/iam-service/pkg/db"

	mock "github.com/stretchr/testify/mock"
)

// InviteManger is an autogenerated mock type for the InviteManger type
type InviteManger struct {
	mock.Mock
}

type InviteManger_Expecter struct {
	mock *mock.Mock
}

func (_m *InviteManger) EXPECT() *InviteManger_Expecter {
	return &InviteManger_Expecter{mock: &_m.Mock}
}

// DeleteInvitesForEmail provides a mock function with given fields: ctx, tenantID, email
func (_m *InviteManger) DeleteInvitesForEmail(ctx context.Context, tenantID string, email string) error {
	ret := _m.Called(ctx, tenantID, email)

	if len(ret) == 0 {
		panic("no return value specified for DeleteInvitesForEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, tenantID, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InviteManger_DeleteInvitesForEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteInvitesForEmail'
type InviteManger_DeleteInvitesForEmail_Call struct {
	*mock.Call
}

// DeleteInvitesForEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - email string
func (_e *InviteManger_Expecter) DeleteInvitesForEmail(ctx interface{}, tenantID interface{}, email interface{}) *InviteManger_DeleteInvitesForEmail_Call {
	return &InviteManger_DeleteInvitesForEmail_Call{Call: _e.mock.On("DeleteInvitesForEmail", ctx, tenantID, email)}
}

func (_c *InviteManger_DeleteInvitesForEmail_Call) Run(run func(ctx context.Context, tenantID string, email string)) *InviteManger_DeleteInvitesForEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *InviteManger_DeleteInvitesForEmail_Call) Return(_a0 error) *InviteManger_DeleteInvitesForEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InviteManger_DeleteInvitesForEmail_Call) RunAndReturn(run func(context.Context, string, string) error) *InviteManger_DeleteInvitesForEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetInvitesForEmail provides a mock function with given fields: ctx, tenantID, email
func (_m *InviteManger) GetInvitesForEmail(ctx context.Context, tenantID string, email string) ([]db.Invite, error) {
	ret := _m.Called(ctx, tenantID, email)

	if len(ret) == 0 {
		panic("no return value specified for GetInvitesForEmail")
	}

	var r0 []db.Invite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]db.Invite, error)); ok {
		return rf(ctx, tenantID, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []db.Invite); ok {
		r0 = rf(ctx, tenantID, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Invite)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, tenantID, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InviteManger_GetInvitesForEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInvitesForEmail'
type InviteManger_GetInvitesForEmail_Call struct {
	*mock.Call
}

// GetInvitesForEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - email string
func (_e *InviteManger_Expecter) GetInvitesForEmail(ctx interface{}, tenantID interface{}, email interface{}) *InviteManger_GetInvitesForEmail_Call {
	return &InviteManger_GetInvitesForEmail_Call{Call: _e.mock.On("GetInvitesForEmail", ctx, tenantID, email)}
}

func (_c *InviteManger_GetInvitesForEmail_Call) Run(run func(ctx context.Context, tenantID string, email string)) *InviteManger_GetInvitesForEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *InviteManger_GetInvitesForEmail_Call) Return(_a0 []db.Invite, _a1 error) *InviteManger_GetInvitesForEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InviteManger_GetInvitesForEmail_Call) RunAndReturn(run func(context.Context, string, string) ([]db.Invite, error)) *InviteManger_GetInvitesForEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewInviteManger creates a new instance of InviteManger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInviteManger(t interface {
	mock.TestingT
	Cleanup(func())
}) *InviteManger {
	mock := &InviteManger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
