// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	graph "github.com/platform-mesh/iam-service/pkg/graph"

	mock "github.com/stretchr/testify/mock"
)

// KeycloakUserChecker is an autogenerated mock type for the KeycloakUserChecker type
type KeycloakUserChecker struct {
	mock.Mock
}

type KeycloakUserChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *KeycloakUserChecker) EXPECT() *KeycloakUserChecker_Expecter {
	return &KeycloakUserChecker_Expecter{mock: &_m.Mock}
}

// UserByMail provides a mock function with given fields: ctx, userID
func (_m *KeycloakUserChecker) UserByMail(ctx context.Context, userID string) (*graph.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for UserByMail")
	}

	var r0 *graph.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*graph.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *graph.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*graph.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KeycloakUserChecker_UserByMail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserByMail'
type KeycloakUserChecker_UserByMail_Call struct {
	*mock.Call
}

// UserByMail is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *KeycloakUserChecker_Expecter) UserByMail(ctx interface{}, userID interface{}) *KeycloakUserChecker_UserByMail_Call {
	return &KeycloakUserChecker_UserByMail_Call{Call: _e.mock.On("UserByMail", ctx, userID)}
}

func (_c *KeycloakUserChecker_UserByMail_Call) Run(run func(ctx context.Context, userID string)) *KeycloakUserChecker_UserByMail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *KeycloakUserChecker_UserByMail_Call) Return(_a0 *graph.User, _a1 error) *KeycloakUserChecker_UserByMail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *KeycloakUserChecker_UserByMail_Call) RunAndReturn(run func(context.Context, string) (*graph.User, error)) *KeycloakUserChecker_UserByMail_Call {
	_c.Call.Return(run)
	return _c
}

// NewKeycloakUserChecker creates a new instance of KeycloakUserChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKeycloakUserChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *KeycloakUserChecker {
	mock := &KeycloakUserChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
