// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// FgaEvents is an autogenerated mock type for the FgaEvents type
type FgaEvents struct {
	mock.Mock
}

type FgaEvents_Expecter struct {
	mock *mock.Mock
}

func (_m *FgaEvents) EXPECT() *FgaEvents_Expecter {
	return &FgaEvents_Expecter{mock: &_m.Mock}
}

// UserRoleChanged provides a mock function with given fields: ctx, tenantID, entityID, entityType, userID, oldRoles, newRoles
func (_m *FgaEvents) UserRoleChanged(ctx context.Context, tenantID string, entityID string, entityType string, userID string, oldRoles []string, newRoles []string) error {
	ret := _m.Called(ctx, tenantID, entityID, entityType, userID, oldRoles, newRoles)

	if len(ret) == 0 {
		panic("no return value specified for UserRoleChanged")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, []string, []string) error); ok {
		r0 = rf(ctx, tenantID, entityID, entityType, userID, oldRoles, newRoles)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FgaEvents_UserRoleChanged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserRoleChanged'
type FgaEvents_UserRoleChanged_Call struct {
	*mock.Call
}

// UserRoleChanged is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - entityID string
//   - entityType string
//   - userID string
//   - oldRoles []string
//   - newRoles []string
func (_e *FgaEvents_Expecter) UserRoleChanged(ctx interface{}, tenantID interface{}, entityID interface{}, entityType interface{}, userID interface{}, oldRoles interface{}, newRoles interface{}) *FgaEvents_UserRoleChanged_Call {
	return &FgaEvents_UserRoleChanged_Call{Call: _e.mock.On("UserRoleChanged", ctx, tenantID, entityID, entityType, userID, oldRoles, newRoles)}
}

func (_c *FgaEvents_UserRoleChanged_Call) Run(run func(ctx context.Context, tenantID string, entityID string, entityType string, userID string, oldRoles []string, newRoles []string)) *FgaEvents_UserRoleChanged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].([]string), args[6].([]string))
	})
	return _c
}

func (_c *FgaEvents_UserRoleChanged_Call) Return(_a0 error) *FgaEvents_UserRoleChanged_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FgaEvents_UserRoleChanged_Call) RunAndReturn(run func(context.Context, string, string, string, string, []string, []string) error) *FgaEvents_UserRoleChanged_Call {
	_c.Call.Return(run)
	return _c
}

// NewFgaEvents creates a new instance of FgaEvents. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFgaEvents(t interface {
	mock.TestingT
	Cleanup(func())
}) *FgaEvents {
	mock := &FgaEvents{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
