// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	graph "github.com/openmfp/iam-service/pkg/graph"

	mock "github.com/stretchr/testify/mock"

	types "github.com/openmfp/iam-service/pkg/fga/types"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// AssignRoleBindings provides a mock function with given fields: ctx, tenantID, entityType, entityID, input
func (_m *Service) AssignRoleBindings(ctx context.Context, tenantID string, entityType string, entityID string, input []*graph.Change) error {
	ret := _m.Called(ctx, tenantID, entityType, entityID, input)

	if len(ret) == 0 {
		panic("no return value specified for AssignRoleBindings")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, []*graph.Change) error); ok {
		r0 = rf(ctx, tenantID, entityType, entityID, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_AssignRoleBindings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignRoleBindings'
type Service_AssignRoleBindings_Call struct {
	*mock.Call
}

// AssignRoleBindings is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - entityType string
//   - entityID string
//   - input []*graph.Change
func (_e *Service_Expecter) AssignRoleBindings(ctx interface{}, tenantID interface{}, entityType interface{}, entityID interface{}, input interface{}) *Service_AssignRoleBindings_Call {
	return &Service_AssignRoleBindings_Call{Call: _e.mock.On("AssignRoleBindings", ctx, tenantID, entityType, entityID, input)}
}

func (_c *Service_AssignRoleBindings_Call) Run(run func(ctx context.Context, tenantID string, entityType string, entityID string, input []*graph.Change)) *Service_AssignRoleBindings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].([]*graph.Change))
	})
	return _c
}

func (_c *Service_AssignRoleBindings_Call) Return(_a0 error) *Service_AssignRoleBindings_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_AssignRoleBindings_Call) RunAndReturn(run func(context.Context, string, string, string, []*graph.Change) error) *Service_AssignRoleBindings_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAccount provides a mock function with given fields: ctx, tenantID, entityType, entityID, ownerUserID
func (_m *Service) CreateAccount(ctx context.Context, tenantID string, entityType string, entityID string, ownerUserID string) error {
	ret := _m.Called(ctx, tenantID, entityType, entityID, ownerUserID)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = rf(ctx, tenantID, entityType, entityID, ownerUserID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_CreateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccount'
type Service_CreateAccount_Call struct {
	*mock.Call
}

// CreateAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - entityType string
//   - entityID string
//   - ownerUserID string
func (_e *Service_Expecter) CreateAccount(ctx interface{}, tenantID interface{}, entityType interface{}, entityID interface{}, ownerUserID interface{}) *Service_CreateAccount_Call {
	return &Service_CreateAccount_Call{Call: _e.mock.On("CreateAccount", ctx, tenantID, entityType, entityID, ownerUserID)}
}

func (_c *Service_CreateAccount_Call) Run(run func(ctx context.Context, tenantID string, entityType string, entityID string, ownerUserID string)) *Service_CreateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *Service_CreateAccount_Call) Return(_a0 error) *Service_CreateAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_CreateAccount_Call) RunAndReturn(run func(context.Context, string, string, string, string) error) *Service_CreateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveAccount provides a mock function with given fields: ctx, tenantID, entityType, entityID
func (_m *Service) RemoveAccount(ctx context.Context, tenantID string, entityType string, entityID string) error {
	ret := _m.Called(ctx, tenantID, entityType, entityID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, tenantID, entityType, entityID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_RemoveAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAccount'
type Service_RemoveAccount_Call struct {
	*mock.Call
}

// RemoveAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - entityType string
//   - entityID string
func (_e *Service_Expecter) RemoveAccount(ctx interface{}, tenantID interface{}, entityType interface{}, entityID interface{}) *Service_RemoveAccount_Call {
	return &Service_RemoveAccount_Call{Call: _e.mock.On("RemoveAccount", ctx, tenantID, entityType, entityID)}
}

func (_c *Service_RemoveAccount_Call) Run(run func(ctx context.Context, tenantID string, entityType string, entityID string)) *Service_RemoveAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *Service_RemoveAccount_Call) Return(_a0 error) *Service_RemoveAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_RemoveAccount_Call) RunAndReturn(run func(context.Context, string, string, string) error) *Service_RemoveAccount_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveFromEntity provides a mock function with given fields: ctx, tenantID, entityType, entityID, userID
func (_m *Service) RemoveFromEntity(ctx context.Context, tenantID string, entityType string, entityID string, userID string) error {
	ret := _m.Called(ctx, tenantID, entityType, entityID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveFromEntity")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = rf(ctx, tenantID, entityType, entityID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_RemoveFromEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveFromEntity'
type Service_RemoveFromEntity_Call struct {
	*mock.Call
}

// RemoveFromEntity is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - entityType string
//   - entityID string
//   - userID string
func (_e *Service_Expecter) RemoveFromEntity(ctx interface{}, tenantID interface{}, entityType interface{}, entityID interface{}, userID interface{}) *Service_RemoveFromEntity_Call {
	return &Service_RemoveFromEntity_Call{Call: _e.mock.On("RemoveFromEntity", ctx, tenantID, entityType, entityID, userID)}
}

func (_c *Service_RemoveFromEntity_Call) Run(run func(ctx context.Context, tenantID string, entityType string, entityID string, userID string)) *Service_RemoveFromEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *Service_RemoveFromEntity_Call) Return(_a0 error) *Service_RemoveFromEntity_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_RemoveFromEntity_Call) RunAndReturn(run func(context.Context, string, string, string, string) error) *Service_RemoveFromEntity_Call {
	_c.Call.Return(run)
	return _c
}

// UsersForEntity provides a mock function with given fields: ctx, tenantID, entityID, entityType
func (_m *Service) UsersForEntity(ctx context.Context, tenantID string, entityID string, entityType string) (types.UserIDToRoles, error) {
	ret := _m.Called(ctx, tenantID, entityID, entityType)

	if len(ret) == 0 {
		panic("no return value specified for UsersForEntity")
	}

	var r0 types.UserIDToRoles
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (types.UserIDToRoles, error)); ok {
		return rf(ctx, tenantID, entityID, entityType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) types.UserIDToRoles); ok {
		r0 = rf(ctx, tenantID, entityID, entityType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.UserIDToRoles)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, tenantID, entityID, entityType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_UsersForEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UsersForEntity'
type Service_UsersForEntity_Call struct {
	*mock.Call
}

// UsersForEntity is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - entityID string
//   - entityType string
func (_e *Service_Expecter) UsersForEntity(ctx interface{}, tenantID interface{}, entityID interface{}, entityType interface{}) *Service_UsersForEntity_Call {
	return &Service_UsersForEntity_Call{Call: _e.mock.On("UsersForEntity", ctx, tenantID, entityID, entityType)}
}

func (_c *Service_UsersForEntity_Call) Run(run func(ctx context.Context, tenantID string, entityID string, entityType string)) *Service_UsersForEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *Service_UsersForEntity_Call) Return(_a0 types.UserIDToRoles, _a1 error) *Service_UsersForEntity_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_UsersForEntity_Call) RunAndReturn(run func(context.Context, string, string, string) (types.UserIDToRoles, error)) *Service_UsersForEntity_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
