// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	rest "k8s.io/client-go/rest"

	v1alpha1 "github.com/kcp-dev/sdk/client/clientset/versioned/typed/core/v1alpha1"
)

// CoreV1alpha1Interface is an autogenerated mock type for the CoreV1alpha1Interface type
type CoreV1alpha1Interface struct {
	mock.Mock
}

type CoreV1alpha1Interface_Expecter struct {
	mock *mock.Mock
}

func (_m *CoreV1alpha1Interface) EXPECT() *CoreV1alpha1Interface_Expecter {
	return &CoreV1alpha1Interface_Expecter{mock: &_m.Mock}
}

// LogicalClusters provides a mock function with no fields
func (_m *CoreV1alpha1Interface) LogicalClusters() v1alpha1.LogicalClusterInterface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LogicalClusters")
	}

	var r0 v1alpha1.LogicalClusterInterface
	if rf, ok := ret.Get(0).(func() v1alpha1.LogicalClusterInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1alpha1.LogicalClusterInterface)
		}
	}

	return r0
}

// CoreV1alpha1Interface_LogicalClusters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogicalClusters'
type CoreV1alpha1Interface_LogicalClusters_Call struct {
	*mock.Call
}

// LogicalClusters is a helper method to define mock.On call
func (_e *CoreV1alpha1Interface_Expecter) LogicalClusters() *CoreV1alpha1Interface_LogicalClusters_Call {
	return &CoreV1alpha1Interface_LogicalClusters_Call{Call: _e.mock.On("LogicalClusters")}
}

func (_c *CoreV1alpha1Interface_LogicalClusters_Call) Run(run func()) *CoreV1alpha1Interface_LogicalClusters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CoreV1alpha1Interface_LogicalClusters_Call) Return(_a0 v1alpha1.LogicalClusterInterface) *CoreV1alpha1Interface_LogicalClusters_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CoreV1alpha1Interface_LogicalClusters_Call) RunAndReturn(run func() v1alpha1.LogicalClusterInterface) *CoreV1alpha1Interface_LogicalClusters_Call {
	_c.Call.Return(run)
	return _c
}

// RESTClient provides a mock function with no fields
func (_m *CoreV1alpha1Interface) RESTClient() rest.Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RESTClient")
	}

	var r0 rest.Interface
	if rf, ok := ret.Get(0).(func() rest.Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rest.Interface)
		}
	}

	return r0
}

// CoreV1alpha1Interface_RESTClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RESTClient'
type CoreV1alpha1Interface_RESTClient_Call struct {
	*mock.Call
}

// RESTClient is a helper method to define mock.On call
func (_e *CoreV1alpha1Interface_Expecter) RESTClient() *CoreV1alpha1Interface_RESTClient_Call {
	return &CoreV1alpha1Interface_RESTClient_Call{Call: _e.mock.On("RESTClient")}
}

func (_c *CoreV1alpha1Interface_RESTClient_Call) Run(run func()) *CoreV1alpha1Interface_RESTClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CoreV1alpha1Interface_RESTClient_Call) Return(_a0 rest.Interface) *CoreV1alpha1Interface_RESTClient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CoreV1alpha1Interface_RESTClient_Call) RunAndReturn(run func() rest.Interface) *CoreV1alpha1Interface_RESTClient_Call {
	_c.Call.Return(run)
	return _c
}

// Shards provides a mock function with no fields
func (_m *CoreV1alpha1Interface) Shards() v1alpha1.ShardInterface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Shards")
	}

	var r0 v1alpha1.ShardInterface
	if rf, ok := ret.Get(0).(func() v1alpha1.ShardInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1alpha1.ShardInterface)
		}
	}

	return r0
}

// CoreV1alpha1Interface_Shards_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shards'
type CoreV1alpha1Interface_Shards_Call struct {
	*mock.Call
}

// Shards is a helper method to define mock.On call
func (_e *CoreV1alpha1Interface_Expecter) Shards() *CoreV1alpha1Interface_Shards_Call {
	return &CoreV1alpha1Interface_Shards_Call{Call: _e.mock.On("Shards")}
}

func (_c *CoreV1alpha1Interface_Shards_Call) Run(run func()) *CoreV1alpha1Interface_Shards_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CoreV1alpha1Interface_Shards_Call) Return(_a0 v1alpha1.ShardInterface) *CoreV1alpha1Interface_Shards_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CoreV1alpha1Interface_Shards_Call) RunAndReturn(run func() v1alpha1.ShardInterface) *CoreV1alpha1Interface_Shards_Call {
	_c.Call.Return(run)
	return _c
}

// NewCoreV1alpha1Interface creates a new instance of CoreV1alpha1Interface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCoreV1alpha1Interface(t interface {
	mock.TestingT
	Cleanup(func())
}) *CoreV1alpha1Interface {
	mock := &CoreV1alpha1Interface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
