// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	cachev1alpha1 "github.com/kcp-dev/sdk/client/clientset/versioned/cluster/typed/cache/v1alpha1"

	corev1alpha1 "github.com/kcp-dev/sdk/client/clientset/versioned/cluster/typed/core/v1alpha1"

	discovery "k8s.io/client-go/discovery"

	logicalcluster "github.com/kcp-dev/logicalcluster/v3"

	mock "github.com/stretchr/testify/mock"

	tenancyv1alpha1 "github.com/kcp-dev/sdk/client/clientset/versioned/cluster/typed/tenancy/v1alpha1"

	topologyv1alpha1 "github.com/kcp-dev/sdk/client/clientset/versioned/cluster/typed/topology/v1alpha1"

	v1alpha1 "github.com/kcp-dev/sdk/client/clientset/versioned/cluster/typed/apis/v1alpha1"

	v1alpha2 "github.com/kcp-dev/sdk/client/clientset/versioned/cluster/typed/apis/v1alpha2"

	versioned "github.com/kcp-dev/sdk/client/clientset/versioned"
)

// ClusterInterface is an autogenerated mock type for the ClusterInterface type
type ClusterInterface struct {
	mock.Mock
}

type ClusterInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *ClusterInterface) EXPECT() *ClusterInterface_Expecter {
	return &ClusterInterface_Expecter{mock: &_m.Mock}
}

// ApisV1alpha1 provides a mock function with no fields
func (_m *ClusterInterface) ApisV1alpha1() v1alpha1.ApisV1alpha1ClusterInterface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ApisV1alpha1")
	}

	var r0 v1alpha1.ApisV1alpha1ClusterInterface
	if rf, ok := ret.Get(0).(func() v1alpha1.ApisV1alpha1ClusterInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1alpha1.ApisV1alpha1ClusterInterface)
		}
	}

	return r0
}

// ClusterInterface_ApisV1alpha1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApisV1alpha1'
type ClusterInterface_ApisV1alpha1_Call struct {
	*mock.Call
}

// ApisV1alpha1 is a helper method to define mock.On call
func (_e *ClusterInterface_Expecter) ApisV1alpha1() *ClusterInterface_ApisV1alpha1_Call {
	return &ClusterInterface_ApisV1alpha1_Call{Call: _e.mock.On("ApisV1alpha1")}
}

func (_c *ClusterInterface_ApisV1alpha1_Call) Run(run func()) *ClusterInterface_ApisV1alpha1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ClusterInterface_ApisV1alpha1_Call) Return(_a0 v1alpha1.ApisV1alpha1ClusterInterface) *ClusterInterface_ApisV1alpha1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ClusterInterface_ApisV1alpha1_Call) RunAndReturn(run func() v1alpha1.ApisV1alpha1ClusterInterface) *ClusterInterface_ApisV1alpha1_Call {
	_c.Call.Return(run)
	return _c
}

// ApisV1alpha2 provides a mock function with no fields
func (_m *ClusterInterface) ApisV1alpha2() v1alpha2.ApisV1alpha2ClusterInterface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ApisV1alpha2")
	}

	var r0 v1alpha2.ApisV1alpha2ClusterInterface
	if rf, ok := ret.Get(0).(func() v1alpha2.ApisV1alpha2ClusterInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1alpha2.ApisV1alpha2ClusterInterface)
		}
	}

	return r0
}

// ClusterInterface_ApisV1alpha2_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApisV1alpha2'
type ClusterInterface_ApisV1alpha2_Call struct {
	*mock.Call
}

// ApisV1alpha2 is a helper method to define mock.On call
func (_e *ClusterInterface_Expecter) ApisV1alpha2() *ClusterInterface_ApisV1alpha2_Call {
	return &ClusterInterface_ApisV1alpha2_Call{Call: _e.mock.On("ApisV1alpha2")}
}

func (_c *ClusterInterface_ApisV1alpha2_Call) Run(run func()) *ClusterInterface_ApisV1alpha2_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ClusterInterface_ApisV1alpha2_Call) Return(_a0 v1alpha2.ApisV1alpha2ClusterInterface) *ClusterInterface_ApisV1alpha2_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ClusterInterface_ApisV1alpha2_Call) RunAndReturn(run func() v1alpha2.ApisV1alpha2ClusterInterface) *ClusterInterface_ApisV1alpha2_Call {
	_c.Call.Return(run)
	return _c
}

// CacheV1alpha1 provides a mock function with no fields
func (_m *ClusterInterface) CacheV1alpha1() cachev1alpha1.CacheV1alpha1ClusterInterface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CacheV1alpha1")
	}

	var r0 cachev1alpha1.CacheV1alpha1ClusterInterface
	if rf, ok := ret.Get(0).(func() cachev1alpha1.CacheV1alpha1ClusterInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cachev1alpha1.CacheV1alpha1ClusterInterface)
		}
	}

	return r0
}

// ClusterInterface_CacheV1alpha1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CacheV1alpha1'
type ClusterInterface_CacheV1alpha1_Call struct {
	*mock.Call
}

// CacheV1alpha1 is a helper method to define mock.On call
func (_e *ClusterInterface_Expecter) CacheV1alpha1() *ClusterInterface_CacheV1alpha1_Call {
	return &ClusterInterface_CacheV1alpha1_Call{Call: _e.mock.On("CacheV1alpha1")}
}

func (_c *ClusterInterface_CacheV1alpha1_Call) Run(run func()) *ClusterInterface_CacheV1alpha1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ClusterInterface_CacheV1alpha1_Call) Return(_a0 cachev1alpha1.CacheV1alpha1ClusterInterface) *ClusterInterface_CacheV1alpha1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ClusterInterface_CacheV1alpha1_Call) RunAndReturn(run func() cachev1alpha1.CacheV1alpha1ClusterInterface) *ClusterInterface_CacheV1alpha1_Call {
	_c.Call.Return(run)
	return _c
}

// Cluster provides a mock function with given fields: _a0
func (_m *ClusterInterface) Cluster(_a0 logicalcluster.Path) versioned.Interface {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Cluster")
	}

	var r0 versioned.Interface
	if rf, ok := ret.Get(0).(func(logicalcluster.Path) versioned.Interface); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(versioned.Interface)
		}
	}

	return r0
}

// ClusterInterface_Cluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cluster'
type ClusterInterface_Cluster_Call struct {
	*mock.Call
}

// Cluster is a helper method to define mock.On call
//   - _a0 logicalcluster.Path
func (_e *ClusterInterface_Expecter) Cluster(_a0 interface{}) *ClusterInterface_Cluster_Call {
	return &ClusterInterface_Cluster_Call{Call: _e.mock.On("Cluster", _a0)}
}

func (_c *ClusterInterface_Cluster_Call) Run(run func(_a0 logicalcluster.Path)) *ClusterInterface_Cluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(logicalcluster.Path))
	})
	return _c
}

func (_c *ClusterInterface_Cluster_Call) Return(_a0 versioned.Interface) *ClusterInterface_Cluster_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ClusterInterface_Cluster_Call) RunAndReturn(run func(logicalcluster.Path) versioned.Interface) *ClusterInterface_Cluster_Call {
	_c.Call.Return(run)
	return _c
}

// CoreV1alpha1 provides a mock function with no fields
func (_m *ClusterInterface) CoreV1alpha1() corev1alpha1.CoreV1alpha1ClusterInterface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CoreV1alpha1")
	}

	var r0 corev1alpha1.CoreV1alpha1ClusterInterface
	if rf, ok := ret.Get(0).(func() corev1alpha1.CoreV1alpha1ClusterInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(corev1alpha1.CoreV1alpha1ClusterInterface)
		}
	}

	return r0
}

// ClusterInterface_CoreV1alpha1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CoreV1alpha1'
type ClusterInterface_CoreV1alpha1_Call struct {
	*mock.Call
}

// CoreV1alpha1 is a helper method to define mock.On call
func (_e *ClusterInterface_Expecter) CoreV1alpha1() *ClusterInterface_CoreV1alpha1_Call {
	return &ClusterInterface_CoreV1alpha1_Call{Call: _e.mock.On("CoreV1alpha1")}
}

func (_c *ClusterInterface_CoreV1alpha1_Call) Run(run func()) *ClusterInterface_CoreV1alpha1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ClusterInterface_CoreV1alpha1_Call) Return(_a0 corev1alpha1.CoreV1alpha1ClusterInterface) *ClusterInterface_CoreV1alpha1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ClusterInterface_CoreV1alpha1_Call) RunAndReturn(run func() corev1alpha1.CoreV1alpha1ClusterInterface) *ClusterInterface_CoreV1alpha1_Call {
	_c.Call.Return(run)
	return _c
}

// Discovery provides a mock function with no fields
func (_m *ClusterInterface) Discovery() discovery.DiscoveryInterface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Discovery")
	}

	var r0 discovery.DiscoveryInterface
	if rf, ok := ret.Get(0).(func() discovery.DiscoveryInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(discovery.DiscoveryInterface)
		}
	}

	return r0
}

// ClusterInterface_Discovery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Discovery'
type ClusterInterface_Discovery_Call struct {
	*mock.Call
}

// Discovery is a helper method to define mock.On call
func (_e *ClusterInterface_Expecter) Discovery() *ClusterInterface_Discovery_Call {
	return &ClusterInterface_Discovery_Call{Call: _e.mock.On("Discovery")}
}

func (_c *ClusterInterface_Discovery_Call) Run(run func()) *ClusterInterface_Discovery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ClusterInterface_Discovery_Call) Return(_a0 discovery.DiscoveryInterface) *ClusterInterface_Discovery_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ClusterInterface_Discovery_Call) RunAndReturn(run func() discovery.DiscoveryInterface) *ClusterInterface_Discovery_Call {
	_c.Call.Return(run)
	return _c
}

// TenancyV1alpha1 provides a mock function with no fields
func (_m *ClusterInterface) TenancyV1alpha1() tenancyv1alpha1.TenancyV1alpha1ClusterInterface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TenancyV1alpha1")
	}

	var r0 tenancyv1alpha1.TenancyV1alpha1ClusterInterface
	if rf, ok := ret.Get(0).(func() tenancyv1alpha1.TenancyV1alpha1ClusterInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(tenancyv1alpha1.TenancyV1alpha1ClusterInterface)
		}
	}

	return r0
}

// ClusterInterface_TenancyV1alpha1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TenancyV1alpha1'
type ClusterInterface_TenancyV1alpha1_Call struct {
	*mock.Call
}

// TenancyV1alpha1 is a helper method to define mock.On call
func (_e *ClusterInterface_Expecter) TenancyV1alpha1() *ClusterInterface_TenancyV1alpha1_Call {
	return &ClusterInterface_TenancyV1alpha1_Call{Call: _e.mock.On("TenancyV1alpha1")}
}

func (_c *ClusterInterface_TenancyV1alpha1_Call) Run(run func()) *ClusterInterface_TenancyV1alpha1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ClusterInterface_TenancyV1alpha1_Call) Return(_a0 tenancyv1alpha1.TenancyV1alpha1ClusterInterface) *ClusterInterface_TenancyV1alpha1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ClusterInterface_TenancyV1alpha1_Call) RunAndReturn(run func() tenancyv1alpha1.TenancyV1alpha1ClusterInterface) *ClusterInterface_TenancyV1alpha1_Call {
	_c.Call.Return(run)
	return _c
}

// TopologyV1alpha1 provides a mock function with no fields
func (_m *ClusterInterface) TopologyV1alpha1() topologyv1alpha1.TopologyV1alpha1ClusterInterface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TopologyV1alpha1")
	}

	var r0 topologyv1alpha1.TopologyV1alpha1ClusterInterface
	if rf, ok := ret.Get(0).(func() topologyv1alpha1.TopologyV1alpha1ClusterInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(topologyv1alpha1.TopologyV1alpha1ClusterInterface)
		}
	}

	return r0
}

// ClusterInterface_TopologyV1alpha1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TopologyV1alpha1'
type ClusterInterface_TopologyV1alpha1_Call struct {
	*mock.Call
}

// TopologyV1alpha1 is a helper method to define mock.On call
func (_e *ClusterInterface_Expecter) TopologyV1alpha1() *ClusterInterface_TopologyV1alpha1_Call {
	return &ClusterInterface_TopologyV1alpha1_Call{Call: _e.mock.On("TopologyV1alpha1")}
}

func (_c *ClusterInterface_TopologyV1alpha1_Call) Run(run func()) *ClusterInterface_TopologyV1alpha1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ClusterInterface_TopologyV1alpha1_Call) Return(_a0 topologyv1alpha1.TopologyV1alpha1ClusterInterface) *ClusterInterface_TopologyV1alpha1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ClusterInterface_TopologyV1alpha1_Call) RunAndReturn(run func() topologyv1alpha1.TopologyV1alpha1ClusterInterface) *ClusterInterface_TopologyV1alpha1_Call {
	_c.Call.Return(run)
	return _c
}

// NewClusterInterface creates a new instance of ClusterInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClusterInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClusterInterface {
	mock := &ClusterInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
