// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	corev1alpha1 "github.com/kcp-dev/sdk/apis/core/v1alpha1"
	mock "github.com/stretchr/testify/mock"

	types "k8s.io/apimachinery/pkg/types"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	v1alpha1 "github.com/kcp-dev/sdk/client/applyconfiguration/core/v1alpha1"

	watch "k8s.io/apimachinery/pkg/watch"
)

// LogicalClusterInterface is an autogenerated mock type for the LogicalClusterInterface type
type LogicalClusterInterface struct {
	mock.Mock
}

type LogicalClusterInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *LogicalClusterInterface) EXPECT() *LogicalClusterInterface_Expecter {
	return &LogicalClusterInterface_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function with given fields: ctx, logicalCluster, opts
func (_m *LogicalClusterInterface) Apply(ctx context.Context, logicalCluster *v1alpha1.LogicalClusterApplyConfiguration, opts v1.ApplyOptions) (*corev1alpha1.LogicalCluster, error) {
	ret := _m.Called(ctx, logicalCluster, opts)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 *corev1alpha1.LogicalCluster
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.LogicalClusterApplyConfiguration, v1.ApplyOptions) (*corev1alpha1.LogicalCluster, error)); ok {
		return rf(ctx, logicalCluster, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.LogicalClusterApplyConfiguration, v1.ApplyOptions) *corev1alpha1.LogicalCluster); ok {
		r0 = rf(ctx, logicalCluster, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1alpha1.LogicalCluster)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1alpha1.LogicalClusterApplyConfiguration, v1.ApplyOptions) error); ok {
		r1 = rf(ctx, logicalCluster, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LogicalClusterInterface_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type LogicalClusterInterface_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - ctx context.Context
//   - logicalCluster *v1alpha1.LogicalClusterApplyConfiguration
//   - opts v1.ApplyOptions
func (_e *LogicalClusterInterface_Expecter) Apply(ctx interface{}, logicalCluster interface{}, opts interface{}) *LogicalClusterInterface_Apply_Call {
	return &LogicalClusterInterface_Apply_Call{Call: _e.mock.On("Apply", ctx, logicalCluster, opts)}
}

func (_c *LogicalClusterInterface_Apply_Call) Run(run func(ctx context.Context, logicalCluster *v1alpha1.LogicalClusterApplyConfiguration, opts v1.ApplyOptions)) *LogicalClusterInterface_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1alpha1.LogicalClusterApplyConfiguration), args[2].(v1.ApplyOptions))
	})
	return _c
}

func (_c *LogicalClusterInterface_Apply_Call) Return(result *corev1alpha1.LogicalCluster, err error) *LogicalClusterInterface_Apply_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *LogicalClusterInterface_Apply_Call) RunAndReturn(run func(context.Context, *v1alpha1.LogicalClusterApplyConfiguration, v1.ApplyOptions) (*corev1alpha1.LogicalCluster, error)) *LogicalClusterInterface_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// ApplyStatus provides a mock function with given fields: ctx, logicalCluster, opts
func (_m *LogicalClusterInterface) ApplyStatus(ctx context.Context, logicalCluster *v1alpha1.LogicalClusterApplyConfiguration, opts v1.ApplyOptions) (*corev1alpha1.LogicalCluster, error) {
	ret := _m.Called(ctx, logicalCluster, opts)

	if len(ret) == 0 {
		panic("no return value specified for ApplyStatus")
	}

	var r0 *corev1alpha1.LogicalCluster
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.LogicalClusterApplyConfiguration, v1.ApplyOptions) (*corev1alpha1.LogicalCluster, error)); ok {
		return rf(ctx, logicalCluster, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.LogicalClusterApplyConfiguration, v1.ApplyOptions) *corev1alpha1.LogicalCluster); ok {
		r0 = rf(ctx, logicalCluster, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1alpha1.LogicalCluster)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1alpha1.LogicalClusterApplyConfiguration, v1.ApplyOptions) error); ok {
		r1 = rf(ctx, logicalCluster, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LogicalClusterInterface_ApplyStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyStatus'
type LogicalClusterInterface_ApplyStatus_Call struct {
	*mock.Call
}

// ApplyStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - logicalCluster *v1alpha1.LogicalClusterApplyConfiguration
//   - opts v1.ApplyOptions
func (_e *LogicalClusterInterface_Expecter) ApplyStatus(ctx interface{}, logicalCluster interface{}, opts interface{}) *LogicalClusterInterface_ApplyStatus_Call {
	return &LogicalClusterInterface_ApplyStatus_Call{Call: _e.mock.On("ApplyStatus", ctx, logicalCluster, opts)}
}

func (_c *LogicalClusterInterface_ApplyStatus_Call) Run(run func(ctx context.Context, logicalCluster *v1alpha1.LogicalClusterApplyConfiguration, opts v1.ApplyOptions)) *LogicalClusterInterface_ApplyStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1alpha1.LogicalClusterApplyConfiguration), args[2].(v1.ApplyOptions))
	})
	return _c
}

func (_c *LogicalClusterInterface_ApplyStatus_Call) Return(result *corev1alpha1.LogicalCluster, err error) *LogicalClusterInterface_ApplyStatus_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *LogicalClusterInterface_ApplyStatus_Call) RunAndReturn(run func(context.Context, *v1alpha1.LogicalClusterApplyConfiguration, v1.ApplyOptions) (*corev1alpha1.LogicalCluster, error)) *LogicalClusterInterface_ApplyStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, logicalCluster, opts
func (_m *LogicalClusterInterface) Create(ctx context.Context, logicalCluster *corev1alpha1.LogicalCluster, opts v1.CreateOptions) (*corev1alpha1.LogicalCluster, error) {
	ret := _m.Called(ctx, logicalCluster, opts)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *corev1alpha1.LogicalCluster
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *corev1alpha1.LogicalCluster, v1.CreateOptions) (*corev1alpha1.LogicalCluster, error)); ok {
		return rf(ctx, logicalCluster, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *corev1alpha1.LogicalCluster, v1.CreateOptions) *corev1alpha1.LogicalCluster); ok {
		r0 = rf(ctx, logicalCluster, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1alpha1.LogicalCluster)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *corev1alpha1.LogicalCluster, v1.CreateOptions) error); ok {
		r1 = rf(ctx, logicalCluster, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LogicalClusterInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type LogicalClusterInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - logicalCluster *corev1alpha1.LogicalCluster
//   - opts v1.CreateOptions
func (_e *LogicalClusterInterface_Expecter) Create(ctx interface{}, logicalCluster interface{}, opts interface{}) *LogicalClusterInterface_Create_Call {
	return &LogicalClusterInterface_Create_Call{Call: _e.mock.On("Create", ctx, logicalCluster, opts)}
}

func (_c *LogicalClusterInterface_Create_Call) Run(run func(ctx context.Context, logicalCluster *corev1alpha1.LogicalCluster, opts v1.CreateOptions)) *LogicalClusterInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*corev1alpha1.LogicalCluster), args[2].(v1.CreateOptions))
	})
	return _c
}

func (_c *LogicalClusterInterface_Create_Call) Return(_a0 *corev1alpha1.LogicalCluster, _a1 error) *LogicalClusterInterface_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LogicalClusterInterface_Create_Call) RunAndReturn(run func(context.Context, *corev1alpha1.LogicalCluster, v1.CreateOptions) (*corev1alpha1.LogicalCluster, error)) *LogicalClusterInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, name, opts
func (_m *LogicalClusterInterface) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	ret := _m.Called(ctx, name, opts)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.DeleteOptions) error); ok {
		r0 = rf(ctx, name, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LogicalClusterInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type LogicalClusterInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts v1.DeleteOptions
func (_e *LogicalClusterInterface_Expecter) Delete(ctx interface{}, name interface{}, opts interface{}) *LogicalClusterInterface_Delete_Call {
	return &LogicalClusterInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, name, opts)}
}

func (_c *LogicalClusterInterface_Delete_Call) Run(run func(ctx context.Context, name string, opts v1.DeleteOptions)) *LogicalClusterInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(v1.DeleteOptions))
	})
	return _c
}

func (_c *LogicalClusterInterface_Delete_Call) Return(_a0 error) *LogicalClusterInterface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LogicalClusterInterface_Delete_Call) RunAndReturn(run func(context.Context, string, v1.DeleteOptions) error) *LogicalClusterInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCollection provides a mock function with given fields: ctx, opts, listOpts
func (_m *LogicalClusterInterface) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	ret := _m.Called(ctx, opts, listOpts)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCollection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, v1.DeleteOptions, v1.ListOptions) error); ok {
		r0 = rf(ctx, opts, listOpts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LogicalClusterInterface_DeleteCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCollection'
type LogicalClusterInterface_DeleteCollection_Call struct {
	*mock.Call
}

// DeleteCollection is a helper method to define mock.On call
//   - ctx context.Context
//   - opts v1.DeleteOptions
//   - listOpts v1.ListOptions
func (_e *LogicalClusterInterface_Expecter) DeleteCollection(ctx interface{}, opts interface{}, listOpts interface{}) *LogicalClusterInterface_DeleteCollection_Call {
	return &LogicalClusterInterface_DeleteCollection_Call{Call: _e.mock.On("DeleteCollection", ctx, opts, listOpts)}
}

func (_c *LogicalClusterInterface_DeleteCollection_Call) Run(run func(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions)) *LogicalClusterInterface_DeleteCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(v1.DeleteOptions), args[2].(v1.ListOptions))
	})
	return _c
}

func (_c *LogicalClusterInterface_DeleteCollection_Call) Return(_a0 error) *LogicalClusterInterface_DeleteCollection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LogicalClusterInterface_DeleteCollection_Call) RunAndReturn(run func(context.Context, v1.DeleteOptions, v1.ListOptions) error) *LogicalClusterInterface_DeleteCollection_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, name, opts
func (_m *LogicalClusterInterface) Get(ctx context.Context, name string, opts v1.GetOptions) (*corev1alpha1.LogicalCluster, error) {
	ret := _m.Called(ctx, name, opts)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *corev1alpha1.LogicalCluster
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.GetOptions) (*corev1alpha1.LogicalCluster, error)); ok {
		return rf(ctx, name, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.GetOptions) *corev1alpha1.LogicalCluster); ok {
		r0 = rf(ctx, name, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1alpha1.LogicalCluster)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, v1.GetOptions) error); ok {
		r1 = rf(ctx, name, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LogicalClusterInterface_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type LogicalClusterInterface_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts v1.GetOptions
func (_e *LogicalClusterInterface_Expecter) Get(ctx interface{}, name interface{}, opts interface{}) *LogicalClusterInterface_Get_Call {
	return &LogicalClusterInterface_Get_Call{Call: _e.mock.On("Get", ctx, name, opts)}
}

func (_c *LogicalClusterInterface_Get_Call) Run(run func(ctx context.Context, name string, opts v1.GetOptions)) *LogicalClusterInterface_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(v1.GetOptions))
	})
	return _c
}

func (_c *LogicalClusterInterface_Get_Call) Return(_a0 *corev1alpha1.LogicalCluster, _a1 error) *LogicalClusterInterface_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LogicalClusterInterface_Get_Call) RunAndReturn(run func(context.Context, string, v1.GetOptions) (*corev1alpha1.LogicalCluster, error)) *LogicalClusterInterface_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *LogicalClusterInterface) List(ctx context.Context, opts v1.ListOptions) (*corev1alpha1.LogicalClusterList, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *corev1alpha1.LogicalClusterList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) (*corev1alpha1.LogicalClusterList, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) *corev1alpha1.LogicalClusterList); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1alpha1.LogicalClusterList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, v1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LogicalClusterInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type LogicalClusterInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts v1.ListOptions
func (_e *LogicalClusterInterface_Expecter) List(ctx interface{}, opts interface{}) *LogicalClusterInterface_List_Call {
	return &LogicalClusterInterface_List_Call{Call: _e.mock.On("List", ctx, opts)}
}

func (_c *LogicalClusterInterface_List_Call) Run(run func(ctx context.Context, opts v1.ListOptions)) *LogicalClusterInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(v1.ListOptions))
	})
	return _c
}

func (_c *LogicalClusterInterface_List_Call) Return(_a0 *corev1alpha1.LogicalClusterList, _a1 error) *LogicalClusterInterface_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LogicalClusterInterface_List_Call) RunAndReturn(run func(context.Context, v1.ListOptions) (*corev1alpha1.LogicalClusterList, error)) *LogicalClusterInterface_List_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function with given fields: ctx, name, pt, data, opts, subresources
func (_m *LogicalClusterInterface) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (*corev1alpha1.LogicalCluster, error) {
	_va := make([]interface{}, len(subresources))
	for _i := range subresources {
		_va[_i] = subresources[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, name, pt, data, opts)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Patch")
	}

	var r0 *corev1alpha1.LogicalCluster
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, types.PatchType, []byte, v1.PatchOptions, ...string) (*corev1alpha1.LogicalCluster, error)); ok {
		return rf(ctx, name, pt, data, opts, subresources...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, types.PatchType, []byte, v1.PatchOptions, ...string) *corev1alpha1.LogicalCluster); ok {
		r0 = rf(ctx, name, pt, data, opts, subresources...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1alpha1.LogicalCluster)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, types.PatchType, []byte, v1.PatchOptions, ...string) error); ok {
		r1 = rf(ctx, name, pt, data, opts, subresources...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LogicalClusterInterface_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type LogicalClusterInterface_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - pt types.PatchType
//   - data []byte
//   - opts v1.PatchOptions
//   - subresources ...string
func (_e *LogicalClusterInterface_Expecter) Patch(ctx interface{}, name interface{}, pt interface{}, data interface{}, opts interface{}, subresources ...interface{}) *LogicalClusterInterface_Patch_Call {
	return &LogicalClusterInterface_Patch_Call{Call: _e.mock.On("Patch",
		append([]interface{}{ctx, name, pt, data, opts}, subresources...)...)}
}

func (_c *LogicalClusterInterface_Patch_Call) Run(run func(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string)) *LogicalClusterInterface_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-5)
		for i, a := range args[5:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(types.PatchType), args[3].([]byte), args[4].(v1.PatchOptions), variadicArgs...)
	})
	return _c
}

func (_c *LogicalClusterInterface_Patch_Call) Return(result *corev1alpha1.LogicalCluster, err error) *LogicalClusterInterface_Patch_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *LogicalClusterInterface_Patch_Call) RunAndReturn(run func(context.Context, string, types.PatchType, []byte, v1.PatchOptions, ...string) (*corev1alpha1.LogicalCluster, error)) *LogicalClusterInterface_Patch_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, logicalCluster, opts
func (_m *LogicalClusterInterface) Update(ctx context.Context, logicalCluster *corev1alpha1.LogicalCluster, opts v1.UpdateOptions) (*corev1alpha1.LogicalCluster, error) {
	ret := _m.Called(ctx, logicalCluster, opts)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *corev1alpha1.LogicalCluster
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *corev1alpha1.LogicalCluster, v1.UpdateOptions) (*corev1alpha1.LogicalCluster, error)); ok {
		return rf(ctx, logicalCluster, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *corev1alpha1.LogicalCluster, v1.UpdateOptions) *corev1alpha1.LogicalCluster); ok {
		r0 = rf(ctx, logicalCluster, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1alpha1.LogicalCluster)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *corev1alpha1.LogicalCluster, v1.UpdateOptions) error); ok {
		r1 = rf(ctx, logicalCluster, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LogicalClusterInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type LogicalClusterInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - logicalCluster *corev1alpha1.LogicalCluster
//   - opts v1.UpdateOptions
func (_e *LogicalClusterInterface_Expecter) Update(ctx interface{}, logicalCluster interface{}, opts interface{}) *LogicalClusterInterface_Update_Call {
	return &LogicalClusterInterface_Update_Call{Call: _e.mock.On("Update", ctx, logicalCluster, opts)}
}

func (_c *LogicalClusterInterface_Update_Call) Run(run func(ctx context.Context, logicalCluster *corev1alpha1.LogicalCluster, opts v1.UpdateOptions)) *LogicalClusterInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*corev1alpha1.LogicalCluster), args[2].(v1.UpdateOptions))
	})
	return _c
}

func (_c *LogicalClusterInterface_Update_Call) Return(_a0 *corev1alpha1.LogicalCluster, _a1 error) *LogicalClusterInterface_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LogicalClusterInterface_Update_Call) RunAndReturn(run func(context.Context, *corev1alpha1.LogicalCluster, v1.UpdateOptions) (*corev1alpha1.LogicalCluster, error)) *LogicalClusterInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, logicalCluster, opts
func (_m *LogicalClusterInterface) UpdateStatus(ctx context.Context, logicalCluster *corev1alpha1.LogicalCluster, opts v1.UpdateOptions) (*corev1alpha1.LogicalCluster, error) {
	ret := _m.Called(ctx, logicalCluster, opts)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 *corev1alpha1.LogicalCluster
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *corev1alpha1.LogicalCluster, v1.UpdateOptions) (*corev1alpha1.LogicalCluster, error)); ok {
		return rf(ctx, logicalCluster, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *corev1alpha1.LogicalCluster, v1.UpdateOptions) *corev1alpha1.LogicalCluster); ok {
		r0 = rf(ctx, logicalCluster, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1alpha1.LogicalCluster)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *corev1alpha1.LogicalCluster, v1.UpdateOptions) error); ok {
		r1 = rf(ctx, logicalCluster, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LogicalClusterInterface_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type LogicalClusterInterface_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - logicalCluster *corev1alpha1.LogicalCluster
//   - opts v1.UpdateOptions
func (_e *LogicalClusterInterface_Expecter) UpdateStatus(ctx interface{}, logicalCluster interface{}, opts interface{}) *LogicalClusterInterface_UpdateStatus_Call {
	return &LogicalClusterInterface_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, logicalCluster, opts)}
}

func (_c *LogicalClusterInterface_UpdateStatus_Call) Run(run func(ctx context.Context, logicalCluster *corev1alpha1.LogicalCluster, opts v1.UpdateOptions)) *LogicalClusterInterface_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*corev1alpha1.LogicalCluster), args[2].(v1.UpdateOptions))
	})
	return _c
}

func (_c *LogicalClusterInterface_UpdateStatus_Call) Return(_a0 *corev1alpha1.LogicalCluster, _a1 error) *LogicalClusterInterface_UpdateStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LogicalClusterInterface_UpdateStatus_Call) RunAndReturn(run func(context.Context, *corev1alpha1.LogicalCluster, v1.UpdateOptions) (*corev1alpha1.LogicalCluster, error)) *LogicalClusterInterface_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Watch provides a mock function with given fields: ctx, opts
func (_m *LogicalClusterInterface) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for Watch")
	}

	var r0 watch.Interface
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) (watch.Interface, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) watch.Interface); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(watch.Interface)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, v1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LogicalClusterInterface_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type LogicalClusterInterface_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - ctx context.Context
//   - opts v1.ListOptions
func (_e *LogicalClusterInterface_Expecter) Watch(ctx interface{}, opts interface{}) *LogicalClusterInterface_Watch_Call {
	return &LogicalClusterInterface_Watch_Call{Call: _e.mock.On("Watch", ctx, opts)}
}

func (_c *LogicalClusterInterface_Watch_Call) Run(run func(ctx context.Context, opts v1.ListOptions)) *LogicalClusterInterface_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(v1.ListOptions))
	})
	return _c
}

func (_c *LogicalClusterInterface_Watch_Call) Return(_a0 watch.Interface, _a1 error) *LogicalClusterInterface_Watch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LogicalClusterInterface_Watch_Call) RunAndReturn(run func(context.Context, v1.ListOptions) (watch.Interface, error)) *LogicalClusterInterface_Watch_Call {
	_c.Call.Return(run)
	return _c
}

// NewLogicalClusterInterface creates a new instance of LogicalClusterInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLogicalClusterInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *LogicalClusterInterface {
	mock := &LogicalClusterInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
