// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	cachev1alpha1 "github.com/kcp-dev/sdk/client/clientset/versioned/typed/cache/v1alpha1"
	corev1alpha1 "github.com/kcp-dev/sdk/client/clientset/versioned/typed/core/v1alpha1"

	discovery "k8s.io/client-go/discovery"

	mock "github.com/stretchr/testify/mock"

	tenancyv1alpha1 "github.com/kcp-dev/sdk/client/clientset/versioned/typed/tenancy/v1alpha1"

	topologyv1alpha1 "github.com/kcp-dev/sdk/client/clientset/versioned/typed/topology/v1alpha1"

	v1alpha1 "github.com/kcp-dev/sdk/client/clientset/versioned/typed/apis/v1alpha1"

	v1alpha2 "github.com/kcp-dev/sdk/client/clientset/versioned/typed/apis/v1alpha2"
)

// Interface is an autogenerated mock type for the Interface type
type Interface struct {
	mock.Mock
}

type Interface_Expecter struct {
	mock *mock.Mock
}

func (_m *Interface) EXPECT() *Interface_Expecter {
	return &Interface_Expecter{mock: &_m.Mock}
}

// ApisV1alpha1 provides a mock function with no fields
func (_m *Interface) ApisV1alpha1() v1alpha1.ApisV1alpha1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ApisV1alpha1")
	}

	var r0 v1alpha1.ApisV1alpha1Interface
	if rf, ok := ret.Get(0).(func() v1alpha1.ApisV1alpha1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1alpha1.ApisV1alpha1Interface)
		}
	}

	return r0
}

// Interface_ApisV1alpha1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApisV1alpha1'
type Interface_ApisV1alpha1_Call struct {
	*mock.Call
}

// ApisV1alpha1 is a helper method to define mock.On call
func (_e *Interface_Expecter) ApisV1alpha1() *Interface_ApisV1alpha1_Call {
	return &Interface_ApisV1alpha1_Call{Call: _e.mock.On("ApisV1alpha1")}
}

func (_c *Interface_ApisV1alpha1_Call) Run(run func()) *Interface_ApisV1alpha1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Interface_ApisV1alpha1_Call) Return(_a0 v1alpha1.ApisV1alpha1Interface) *Interface_ApisV1alpha1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Interface_ApisV1alpha1_Call) RunAndReturn(run func() v1alpha1.ApisV1alpha1Interface) *Interface_ApisV1alpha1_Call {
	_c.Call.Return(run)
	return _c
}

// ApisV1alpha2 provides a mock function with no fields
func (_m *Interface) ApisV1alpha2() v1alpha2.ApisV1alpha2Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ApisV1alpha2")
	}

	var r0 v1alpha2.ApisV1alpha2Interface
	if rf, ok := ret.Get(0).(func() v1alpha2.ApisV1alpha2Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1alpha2.ApisV1alpha2Interface)
		}
	}

	return r0
}

// Interface_ApisV1alpha2_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApisV1alpha2'
type Interface_ApisV1alpha2_Call struct {
	*mock.Call
}

// ApisV1alpha2 is a helper method to define mock.On call
func (_e *Interface_Expecter) ApisV1alpha2() *Interface_ApisV1alpha2_Call {
	return &Interface_ApisV1alpha2_Call{Call: _e.mock.On("ApisV1alpha2")}
}

func (_c *Interface_ApisV1alpha2_Call) Run(run func()) *Interface_ApisV1alpha2_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Interface_ApisV1alpha2_Call) Return(_a0 v1alpha2.ApisV1alpha2Interface) *Interface_ApisV1alpha2_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Interface_ApisV1alpha2_Call) RunAndReturn(run func() v1alpha2.ApisV1alpha2Interface) *Interface_ApisV1alpha2_Call {
	_c.Call.Return(run)
	return _c
}

// CacheV1alpha1 provides a mock function with no fields
func (_m *Interface) CacheV1alpha1() cachev1alpha1.CacheV1alpha1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CacheV1alpha1")
	}

	var r0 cachev1alpha1.CacheV1alpha1Interface
	if rf, ok := ret.Get(0).(func() cachev1alpha1.CacheV1alpha1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cachev1alpha1.CacheV1alpha1Interface)
		}
	}

	return r0
}

// Interface_CacheV1alpha1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CacheV1alpha1'
type Interface_CacheV1alpha1_Call struct {
	*mock.Call
}

// CacheV1alpha1 is a helper method to define mock.On call
func (_e *Interface_Expecter) CacheV1alpha1() *Interface_CacheV1alpha1_Call {
	return &Interface_CacheV1alpha1_Call{Call: _e.mock.On("CacheV1alpha1")}
}

func (_c *Interface_CacheV1alpha1_Call) Run(run func()) *Interface_CacheV1alpha1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Interface_CacheV1alpha1_Call) Return(_a0 cachev1alpha1.CacheV1alpha1Interface) *Interface_CacheV1alpha1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Interface_CacheV1alpha1_Call) RunAndReturn(run func() cachev1alpha1.CacheV1alpha1Interface) *Interface_CacheV1alpha1_Call {
	_c.Call.Return(run)
	return _c
}

// CoreV1alpha1 provides a mock function with no fields
func (_m *Interface) CoreV1alpha1() corev1alpha1.CoreV1alpha1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CoreV1alpha1")
	}

	var r0 corev1alpha1.CoreV1alpha1Interface
	if rf, ok := ret.Get(0).(func() corev1alpha1.CoreV1alpha1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(corev1alpha1.CoreV1alpha1Interface)
		}
	}

	return r0
}

// Interface_CoreV1alpha1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CoreV1alpha1'
type Interface_CoreV1alpha1_Call struct {
	*mock.Call
}

// CoreV1alpha1 is a helper method to define mock.On call
func (_e *Interface_Expecter) CoreV1alpha1() *Interface_CoreV1alpha1_Call {
	return &Interface_CoreV1alpha1_Call{Call: _e.mock.On("CoreV1alpha1")}
}

func (_c *Interface_CoreV1alpha1_Call) Run(run func()) *Interface_CoreV1alpha1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Interface_CoreV1alpha1_Call) Return(_a0 corev1alpha1.CoreV1alpha1Interface) *Interface_CoreV1alpha1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Interface_CoreV1alpha1_Call) RunAndReturn(run func() corev1alpha1.CoreV1alpha1Interface) *Interface_CoreV1alpha1_Call {
	_c.Call.Return(run)
	return _c
}

// Discovery provides a mock function with no fields
func (_m *Interface) Discovery() discovery.DiscoveryInterface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Discovery")
	}

	var r0 discovery.DiscoveryInterface
	if rf, ok := ret.Get(0).(func() discovery.DiscoveryInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(discovery.DiscoveryInterface)
		}
	}

	return r0
}

// Interface_Discovery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Discovery'
type Interface_Discovery_Call struct {
	*mock.Call
}

// Discovery is a helper method to define mock.On call
func (_e *Interface_Expecter) Discovery() *Interface_Discovery_Call {
	return &Interface_Discovery_Call{Call: _e.mock.On("Discovery")}
}

func (_c *Interface_Discovery_Call) Run(run func()) *Interface_Discovery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Interface_Discovery_Call) Return(_a0 discovery.DiscoveryInterface) *Interface_Discovery_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Interface_Discovery_Call) RunAndReturn(run func() discovery.DiscoveryInterface) *Interface_Discovery_Call {
	_c.Call.Return(run)
	return _c
}

// TenancyV1alpha1 provides a mock function with no fields
func (_m *Interface) TenancyV1alpha1() tenancyv1alpha1.TenancyV1alpha1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TenancyV1alpha1")
	}

	var r0 tenancyv1alpha1.TenancyV1alpha1Interface
	if rf, ok := ret.Get(0).(func() tenancyv1alpha1.TenancyV1alpha1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(tenancyv1alpha1.TenancyV1alpha1Interface)
		}
	}

	return r0
}

// Interface_TenancyV1alpha1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TenancyV1alpha1'
type Interface_TenancyV1alpha1_Call struct {
	*mock.Call
}

// TenancyV1alpha1 is a helper method to define mock.On call
func (_e *Interface_Expecter) TenancyV1alpha1() *Interface_TenancyV1alpha1_Call {
	return &Interface_TenancyV1alpha1_Call{Call: _e.mock.On("TenancyV1alpha1")}
}

func (_c *Interface_TenancyV1alpha1_Call) Run(run func()) *Interface_TenancyV1alpha1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Interface_TenancyV1alpha1_Call) Return(_a0 tenancyv1alpha1.TenancyV1alpha1Interface) *Interface_TenancyV1alpha1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Interface_TenancyV1alpha1_Call) RunAndReturn(run func() tenancyv1alpha1.TenancyV1alpha1Interface) *Interface_TenancyV1alpha1_Call {
	_c.Call.Return(run)
	return _c
}

// TopologyV1alpha1 provides a mock function with no fields
func (_m *Interface) TopologyV1alpha1() topologyv1alpha1.TopologyV1alpha1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TopologyV1alpha1")
	}

	var r0 topologyv1alpha1.TopologyV1alpha1Interface
	if rf, ok := ret.Get(0).(func() topologyv1alpha1.TopologyV1alpha1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(topologyv1alpha1.TopologyV1alpha1Interface)
		}
	}

	return r0
}

// Interface_TopologyV1alpha1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TopologyV1alpha1'
type Interface_TopologyV1alpha1_Call struct {
	*mock.Call
}

// TopologyV1alpha1 is a helper method to define mock.On call
func (_e *Interface_Expecter) TopologyV1alpha1() *Interface_TopologyV1alpha1_Call {
	return &Interface_TopologyV1alpha1_Call{Call: _e.mock.On("TopologyV1alpha1")}
}

func (_c *Interface_TopologyV1alpha1_Call) Run(run func()) *Interface_TopologyV1alpha1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Interface_TopologyV1alpha1_Call) Return(_a0 topologyv1alpha1.TopologyV1alpha1Interface) *Interface_TopologyV1alpha1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Interface_TopologyV1alpha1_Call) RunAndReturn(run func() topologyv1alpha1.TopologyV1alpha1Interface) *Interface_TopologyV1alpha1_Call {
	_c.Call.Return(run)
	return _c
}

// NewInterface creates a new instance of Interface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *Interface {
	mock := &Interface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
