name: ci
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  pipe:
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    uses: platform-mesh/.github/.github/workflows/pipeline-golang-app.yml@07550bab80de7691f4947214ee342351896e209b # main
    secrets: inherit
    with:
      imageTagName: ghcr.io/platform-mesh/iam-service
      useLocalCoverageConfig: true
      useTask: true

  quality-gate:
    permissions: {}
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - run: echo "OK"
